#!/bin/sh

# ci_post_clone.sh
# Runs automatically after Xcode Cloud clones the repository.
# Generates Secrets.xcconfig from Xcode Cloud environment variables.
# Define these in Xcode Cloud → Workflows → Environment → Secrets:
#   VOTICE_API_KEY, VOTICE_API_SECRET, VOTICE_APP_ID

set -e

REPO_ROOT="$(dirname "$0")/.."
SECRETS_FILE="$REPO_ROOT/Secrets.xcconfig"

cat > "$SECRETS_FILE" << EOF
// Secrets.xcconfig — generated by ci_post_clone.sh
VOTICE_API_KEY = ${VOTICE_API_KEY:-}
VOTICE_API_SECRET = ${VOTICE_API_SECRET:-}
VOTICE_APP_ID = ${VOTICE_APP_ID:-}
EOF

echo "✅ Secrets.xcconfig generated at $SECRETS_FILE"